### ISSUE TITLE
idh-setup error: Recurse failed: none of the specified sources were found

### ISSUE THREAD

**Issue by SuiNom** [defensivedepth/so-idh#6]
Hi, just documented some issues I've had attempting to use the idh-setup scripts on a brand new distributed SecurityOnion setup running `2.3.91`.

After running the `idh-setup.sh` script on a MANAGERSEARCH node, selecting a SENSOR node, I get the generic  error during setup, and upon reviewing the `/root/ish-setup.log` file, there appears to be only one failing task.
```
----------
          ID: idhfiles
    Function: file.recurse
        Name: /opt/so/conf/idh
      Result: False
     Comment: Recurse failed: none of the specified sources were found
     Started: 10:13:24.192324
    Duration: 56.672 ms
     Changes:   
----------

```

Which looks to relate to this section of the `init.sls`:
```
# Sync IDH files
idhfiles:
  file.recurse:
    - name: /opt/so/conf/idh
    - user: 0
    - group: 0
    - file_mode: 755
    - source: salt://idh/config
    - replace: False
    - template: jinja
```
I'm not fully conversant with salt so I thought I'd do some digging around, the user/group id's looked a little off but I haven't changed them yet.
I thought it should probably be the same `939` user and group (so-core?), but wanted to get this all noted down before I start troubleshooting too hard.

I thought I'd do some digging around on the sensor instead, looking at the configs that were created, etc and noticed that `opencanary.conf` is a directory, rather than a file:
```
[root@security-onion-distrib-1 idh]# pwd && ll -a
/opt/so/conf/idh
total 0
drwxr-xr-x.  3 socore socore  29 Jan 18 10:14 .
drwxrwx---. 15 root   root   264 Jan 18 10:13 ..
drwxr-xr-x.  2 root   root     6 Jan 18 10:14 opencanary.conf
```
and a quick `docker ps` shows me the `so-idh` container isn't binding to any ports, so we're not getting very far with it.

I'd love to collaborate on this one, as from the conference it seemed like a great use case we'd like to explore.

**Comment by SuiNom** [comment]
Okay, some further poking and prodding and I've figured out a little more (hopefully correct) information.

1. I changed the user and group listed in `idhfiles:` section of `init.sls` to `939`, which I confirmed was the `socore` user.
2. Deleted the `opencanary.conf` directory that was created.
3. re-ran the `idh-setup.sh` script
4. Success!

I now seem to have a working IDH node, I can test it using ssh and get playbook alerts. 
I'm just wondering if there's a reason those user/group variables for the file sync are set to 0 out of the box?

As a side note I was still confused that `docker ps` showed no ports being bound by the container, but `netstat -lntp` showed me python listening on both 2222 and 5900 TCP. Then I reviewed the `init.sls` again and noticed the network mode is set to `host`:
```
# Set IDH Docker to run
so-idh-run:
  docker_container.running:
    - image: so-idh
    - name: so-idh
    - detach: True
    - network_mode: host
    - restart_policy: always
    - binds:
      - /nsm/idh:/var/tmp:rw
      - /opt/so/conf/idh/opencanary.conf:/etc/opencanaryd/opencanary.conf:ro
```

I'm assuming this is so the code doesn't have to parse the opencanary config for which ports are in use, and insert them into the salt call to start the container with the bound ports? (seemed like a clever solution to me!)
